trigger:
  batch: true
  branches:
    include:
    - refs/heads/main
  paths:
    include:
    - DataFiles**/*

variables:
- template: variables.yaml

pool: 
  vmImage: windows-latest

stages:
  - stage: M365DSCBuild
    displayName: 'Microsoft365DSC build'
    jobs:
    - job: CompileConfiguration
      displayName: 'Compile configuration MOF files'
      steps:
      - task: CmdLine@2
        displayName: 'Configure WinRM'
        inputs:
          script: |
            @echo on
            call winrm invoke restore winrm/config
            call winrm quickconfig -quiet
            call winrm set winrm/config @{MaxEnvelopeSizekb="4096"} > null
            call winrm get winrm/config | find /i "MaxEnvelopeSizekb"

      - task: AzurePowerShell@5
        displayName: 'Download secrets'
        inputs:
          ScriptType: 'FilePath'
          ScriptPath: './DownloadSecrets.ps1'
          ScriptArguments: '-KeyVault "${{ variables.keyVault }}"'
          azurePowerShellVersion: 'latestVersion'
          azureSubscription: '${{ variables.azureSubscription }}'
          errorActionPreference: 'Stop'
          FailOnStandardError: true

      - task: PowerShell@2
        displayName: 'Compile artifacts'
        inputs:
          targetType: 'filePath'
          filePath: './Build.ps1'
          arguments: '-PackageSourceLocation "${{ variables.packageSourceLocation }}" -PATToken "$(patToken)"'
          errorActionPreference: 'Stop'
          failOnStderr: true

      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifacts to pipeline'
        inputs:
          targetPath: '${{ variables.buildFolderName }}/'
          artifact: '${{ variables.buildArtifactName }}'
          publishLocation: 'pipeline'
          parallel: true
